_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_main:
    resource: routing.yml

oro_ews_email:
    resource: "@OroEwsEmailBundle/Resources/config/routing.yml"
    prefix:   /

oro_ews_calendar:
    resource: "@OroEwsCalendarBundle/Resources/config/routing.yml"
    prefix:   /
