#
# 3rd party routes
#
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

#
# OROCRM routes
#
orocrm_contact:
    resource: "@OroCRMContactBundle/Resources/config/routing.yml"

orocrm_account:
    resource: "@OroCRMAccountBundle/Resources/config/routing.yml"

orocrm_sales:
    resource: "@OroCRMSalesBundle/Resources/config/routing.yml"
    prefix:   /sales

orocrm_report:
    resource: "@OroCRMReportBundle/Resources/config/routing.yml"

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        template:    OroCRMDashboardBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_auto_routing:
    resource: .
    type:     oro_auto