oro_menu_config:
    items:
        home:
            name: 'Home'
            label: ''
            extras:
                icon: 'icon-home icon-white'
                position: 1
            route: 'oro_default'

oro_titles:
    oro_default: Dashboard
